baseURL = 'ongshunping.com'
languageCode = 'en-us'
title = "Shunping's Blog"
theme = 'hugo-tania'
paginate = 6

[params]
# Emoji will show before the blog title on site navbar.
titleEmoji = "☃️"

# Logo will show before the blog title on site navbar.
titleLogo = ""

# Enable float footnotes.
# Default to true
enableFootnotes = true

siteName = "Shunping's Blog"
siteDesc = "👋"
author = "Ong Shun Ping"

[params.colorScheme]
# Enable toggle colorScheme
# Default to true
toggle = true
# Default colorScheme
# Default to auto
#default = auto

# Limit how many categories filter show above search input.
# Default to 5
maxCategoryToShow = 10

# Show your social information with icon on index bio with `_index.md` content.
[params.socialOptions]
dev-to = ""
email = "ongshunping@hotmail.com"
facebook = ""
github = "https://github.com/ongshunping"
instagram = ""
linkedin = "https://www.linkedin.com/in/ongshunping/"
medium = ""
stack-overflow = ""
steam = ""
telegram = ""
twitter = ""
twitch = ""
whatsapp = ""

# Comments settings
[params.comments]
enabled = true
provider = "disqus"

[menu]
[[menu.header]]
name = "Archives"
url = "/Archives/"

[markup]
[markup.highlight]
noClasses = false
lineNos = true
[markup.goldmark.renderer]
unsafe = true

[outputs]
home = ["HTML", "RSS", "JSON"]